---
name: container image

on:
  push:
  pull_request:
  schedule:
  - cron: '0 20 * * 5'

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    permissions: {packages: write}
    steps:
    - uses: docker/setup-qemu-action@v3.2.0
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3.8.0
    # > By default, this action uses the Git context so you don't need to use
    # > the actions/checkout action to checkout the repository because this
    # > will be done directly by buildkit. [...]
    # > any file mutation in the steps that precede [...] will be ignored,
    # > including processing of the .dockerignore file
    # https://github.com/marketplace/actions/build-and-push-docker-images
    # > The commit history is not preserved.
    # https://docs.docker.com/engine/reference/commandline/build/#git-repositories
    - uses: docker/build-push-action@v6.10.0
      with:
        build-args: | # git history unavailable (see above)
          SETUPTOOLS_SCM_PRETEND_VERSION=0
        platforms: |
          linux/amd64
          linux/arm/v6
          linux/arm/v7
          linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.actor }}/systemctl-mqtt:${{ github.sha }}-attempt${{ github.run_attempt }}
